spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/cooperfilme_production?useSSL=false&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false

server:
  port: 8080

cooper:
  jwt:
    secret: verysecretkeychangeit
    expiration-ms: 86400000
